name: Go Tests
on: [push, pull_request]
jobs:
  go_tests:
    runs-on: windows-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test -v ./...
